# Generated by Django 6.0.3 on 2026-03-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='orders_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
    ]
