# Generated by Django 6.0.3 on 2026-04-01 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_sellerprofile_orders_completed_sellerprofile_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='photo',
            field=models.ImageField(default='default-profile.png', upload_to='buyer_profiles/'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='photo',
            field=models.ImageField(default='default-profile.png', upload_to='seller_profiles/'),
        ),
    ]
