# Generated by Django 6.0.3 on 2026-04-01 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_buyerprofile_photo_alter_sellerprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='photo',
            field=models.ImageField(default='buyer_profiles/default.png', upload_to='buyer_profiles/'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='photo',
            field=models.ImageField(default='seller_profiles/default.png', upload_to='seller_profiles/'),
        ),
    ]
