# Generated by Django 6.0.3 on 2026-04-05 19:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_local', '0004_user_is_buyer_user_is_seller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyerprofile',
            options={'verbose_name': 'Buyer Profile', 'verbose_name_plural': 'Buyer Profiles'},
        ),
        migrations.AlterModelOptions(
            name='sellerprofile',
            options={'verbose_name': 'Seller Profile', 'verbose_name_plural': 'Seller Profiles'},
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
